/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {
    Game game = new Game();
    game.setVisible(true);
  }
}
